spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/epamcourses?currentSchema=liadov
    username: postgres
    password: postgres
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  enabled: true